server:
  port: 9001


mybatis:
  type-aliases-package: com.gavin.websocket
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/DB?characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver
